#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("iPark.Droid.Resource", IsApplication=true)]

namespace iPark.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::iPark.Data.Droid.Resource.String.library_name = global::iPark.Droid.Resource.String.library_name;
			global::Xamarin.Forms.Platform.Resource.String.ApplicationName = global::iPark.Droid.Resource.String.ApplicationName;
			global::Xamarin.Forms.Platform.Resource.String.Hello = global::iPark.Droid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int LogoGrande = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int LogoPequeno = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Mapa = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Park = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ps_top_card_01 = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050002
			public const int autoCompleteTextViewUsername = 2131034114;
			
			// aapt resource value: 0x7f050008
			public const int buttonLogin = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int buttonLoginFacebook = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int buttonLoginGoogle = 2131034122;
			
			// aapt resource value: 0x7f050013
			public const int buttonParksListView = 2131034131;
			
			// aapt resource value: 0x7f05000c
			public const int buttonParksMapView = 2131034124;
			
			// aapt resource value: 0x7f050004
			public const int editTextPassword = 2131034116;
			
			// aapt resource value: 0x7f050000
			public const int imageLogo = 2131034112;
			
			// aapt resource value: 0x7f050014
			public const int imageMapa = 2131034132;
			
			// aapt resource value: 0x7f05000e
			public const int imagePark = 2131034126;
			
			// aapt resource value: 0x7f05000d
			public const int listviewParks = 2131034125;
			
			// aapt resource value: 0x7f050010
			public const int textCompany = 2131034128;
			
			// aapt resource value: 0x7f05000f
			public const int textName = 2131034127;
			
			// aapt resource value: 0x7f050012
			public const int textPrice = 2131034130;
			
			// aapt resource value: 0x7f050011
			public const int textTimetable = 2131034129;
			
			// aapt resource value: 0x7f050005
			public const int textView = 2131034117;
			
			// aapt resource value: 0x7f05000b
			public const int textViewAnonymous = 2131034123;
			
			// aapt resource value: 0x7f050003
			public const int textViewPassword = 2131034115;
			
			// aapt resource value: 0x7f050006
			public const int textViewPasswordRecover = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int textViewRegister = 2131034119;
			
			// aapt resource value: 0x7f050001
			public const int textViewUsername = 2131034113;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ParksListView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ParksListView_row = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ParksMapView = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ParksSingleView = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int ApplicationName = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int GoogleMapsAPIKey = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Hello = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int library_name = 2130968579;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
